/**
 * HelloAgents 工具系统的基础抽象。
 *
 * TypeScript 运行时不会保留完整的类型注解，因此自动展开工具时会优先根据
 * 默认值推断参数类型；无法推断的参数统一按字符串处理，这与模型生成文本参数
 * 的常见使用方式相符。
 */

import {
  TOOL_ACTION_METADATA,
  type DecoratedToolAction,
  type ToolActionMethod,
} from "./decorator";

// 便于工具使用方从统一入口获取装饰器，无需感知内部文件划分。
export { toolAction } from "./decorator";

/** OpenAI function calling 支持的基础 JSON Schema 类型。 */
export type ToolParameterType =
  | "string"
  | "integer"
  | "number"
  | "boolean"
  | "array"
  | "object";

/** 创建工具参数时使用的完整配置。 */
export interface ToolParameterOptions {
  name: string;
  type: ToolParameterType | string;
  description: string;
  required?: boolean;
  default?: unknown;
}

/** 工具参数定义，作用等同于 Python 版本中的 Pydantic 模型。 */
export class ToolParameter {
  name: string;
  type: ToolParameterType | string;
  description: string;
  required: boolean;
  default: unknown;

  constructor(options: ToolParameterOptions) {
    this.name = options.name;
    this.type = options.type;
    this.description = options.description;
    this.required = options.required ?? true;
    this.default = options.default ?? null;
  }

  /** 返回普通对象，便于序列化并保持 Python `dict()` 的输出形状。 */
  toJSON(): Required<ToolParameterOptions> {
    return {
      name: this.name,
      type: this.type,
      description: this.description,
      required: this.required,
      default: this.default,
    };
  }
}

/** 工具序列化后的稳定数据结构。 */
export interface ToolDefinition {
  name: string;
  description: string;
  parameters: Required<ToolParameterOptions>[];
}

/** OpenAI function calling 所需的函数 schema。 */
export interface OpenAIToolSchema {
  type: "function";
  function: {
    name: string;
    description: string;
    parameters: {
      type: "object";
      properties: Record<string, Record<string, unknown>>;
      required: string[];
    };
  };
}

/**
 * 所有工具的抽象基类。
 *
 * 子类只需实现 `run` 与 `getParameters`。当 `expandable` 为 true 时，
 * 默认的 `getExpandedTools` 会沿原型链查找带有 `@toolAction` 的方法。
 */
export abstract class Tool {
  readonly name: string;
  readonly description: string;
  readonly expandable: boolean;

  constructor(name: string, description: string, expandable = false) {
    this.name = name;
    this.description = description;
    this.expandable = expandable;
  }

  /** 执行工具；本地计算可同步返回，网络或 I/O 工具可以返回 Promise。 */
  abstract run(parameters: Record<string, unknown>): string | Promise<string>;

  /** 返回供参数校验、提示词生成和 function calling 使用的参数声明。 */
  abstract getParameters(): ToolParameter[];

  /**
   * 自动生成所有被装饰的子工具。
   *
   * 从实例自身开始向上遍历原型链，可同时覆盖实例函数、继承方法和重写方法。
   * `visitedNames` 确保子类重写的方法优先，避免同名父类方法被重复展开。
   */
  getExpandedTools(): Tool[] | undefined {
    if (!this.expandable) return undefined;

    const tools: Tool[] = [];
    const visitedNames = new Set<string>();
    let current: object | null = this;

    while (current && current !== Tool.prototype) {
      for (const propertyName of Object.getOwnPropertyNames(current)) {
        if (propertyName === "constructor" || visitedNames.has(propertyName)) continue;
        visitedNames.add(propertyName);

        const descriptor = Object.getOwnPropertyDescriptor(current, propertyName);
        const candidate = descriptor?.value as DecoratedToolAction | undefined;
        const metadata = candidate?.[TOOL_ACTION_METADATA];
        if (typeof candidate !== "function" || !metadata) continue;

        tools.push(
          new AutoGeneratedTool(
            this,
            candidate,
            metadata.name,
            metadata.description,
            metadata.methodName,
          ),
        );
      }

      current = Object.getPrototypeOf(current) as object | null;
    }

    return tools.length > 0 ? tools : undefined;
  }

  /** 只检查必填参数是否存在；具体类型转换由 Agent 或工具自身完成。 */
  validateParameters(parameters: Record<string, unknown>): boolean {
    return this.getParameters()
      .filter((parameter) => parameter.required)
      .every((parameter) => Object.prototype.hasOwnProperty.call(parameters, parameter.name));
  }

  /** 转换为可直接 JSON 序列化的工具描述。 */
  toDict(): ToolDefinition {
    return {
      name: this.name,
      description: this.description,
      parameters: this.getParameters().map((parameter) => parameter.toJSON()),
    };
  }

  /** 转换为 OpenAI 原生 function calling schema。 */
  toOpenAISchema(): OpenAIToolSchema {
    const properties: Record<string, Record<string, unknown>> = {};
    const required: string[] = [];

    for (const parameter of this.getParameters()) {
      const property: Record<string, unknown> = {
        type: parameter.type,
        description:
          parameter.default === null || parameter.default === undefined
            ? parameter.description
            : `${parameter.description} (默认: ${String(parameter.default)})`,
      };

      // OpenAI schema 的数组必须提供 items；与 Python 版本一样默认按字符串数组处理。
      if (parameter.type === "array") property.items = { type: "string" };
      properties[parameter.name] = property;
      if (parameter.required) required.push(parameter.name);
    }

    return {
      type: "function",
      function: {
        name: this.name,
        description: this.description,
        parameters: { type: "object", properties, required },
      },
    };
  }

  toString(): string {
    return `Tool(name=${this.name})`;
  }
}

/**
 * 由带装饰器的方法自动构造的工具。
 *
 * JavaScript 没有 Python `inspect.signature` 的完整等价物，因此这里只解析普通的
 * 标识符参数和常见字面量默认值。解构参数仍可执行，但无法可靠生成模型可用的
 * 参数名，遇到这类签名会明确报错，促使调用方改用手动工具定义。
 */
export class AutoGeneratedTool extends Tool {
  private readonly parent: Tool;
  private readonly method: ToolActionMethod;
  private readonly parameters: ToolParameter[];
  private readonly methodName: string;

  constructor(
    parent: Tool,
    method: ToolActionMethod,
    name?: string,
    description?: string,
    methodName?: string,
  ) {
    const resolvedMethodName = methodName ?? method.name.replace(/^bound\s+/, "");
    const normalizedMethodName = resolvedMethodName.replace(/^_+/, "");
    super(
      name ?? `${parent.name}_${normalizedMethodName}`,
      description ?? AutoGeneratedTool.extractDescription(method, resolvedMethodName),
    );

    this.parent = parent;
    this.method = method;
    this.methodName = resolvedMethodName;
    this.parameters = this.parseParameters();
  }

  /** JS 的函数源码通常不含前置 JSDoc，因此无显式描述时使用稳定的回退文本。 */
  private static extractDescription(method: ToolActionMethod, methodName: string): string {
    const source = Function.prototype.toString.call(method);
    const inlineComment = source.match(/^[^{]*{\s*\/\*\*?\s*([^*@\n][^*]*)\*\//)?.[1];
    return inlineComment?.trim() || `执行 ${methodName}`;
  }

  /** 从方法源码提取参数名、是否必填以及可安全识别的默认值。 */
  private parseParameters(): ToolParameter[] {
    const source = Function.prototype.toString.call(this.method);
    const openingParenthesis = source.indexOf("(");
    const closingParenthesis = AutoGeneratedTool.findClosingParenthesis(
      source,
      openingParenthesis,
    );

    if (openingParenthesis < 0 || closingParenthesis < 0) return [];
    const parameterSource = source.slice(openingParenthesis + 1, closingParenthesis);

    return AutoGeneratedTool.splitTopLevel(parameterSource).map((rawParameter) => {
      const cleaned = rawParameter.replace(/\/\*[\s\S]*?\*\//g, "").trim();
      const assignmentIndex = AutoGeneratedTool.findTopLevelAssignment(cleaned);
      const rawName = (assignmentIndex < 0 ? cleaned : cleaned.slice(0, assignmentIndex))
        .replace(/^\.\.\./, "")
        .trim();

      if (!/^[A-Za-z_$][\w$]*$/.test(rawName)) {
        throw new TypeError(
          `无法为方法 '${this.methodName}' 的解构参数 '${rawName}' 自动生成工具声明`,
        );
      }

      const required = assignmentIndex < 0;
      const defaultValue = required
        ? null
        : AutoGeneratedTool.parseLiteral(cleaned.slice(assignmentIndex + 1).trim());

      return new ToolParameter({
        name: rawName,
        type: AutoGeneratedTool.inferToolType(defaultValue),
        description: `参数 ${rawName}`,
        required,
        default: defaultValue,
      });
    });
  }

  /** 定位与参数列表左括号匹配的右括号，同时忽略字符串中的括号。 */
  private static findClosingParenthesis(source: string, openingIndex: number): number {
    if (openingIndex < 0) return -1;
    let depth = 0;
    let quote: string | undefined;

    for (let index = openingIndex; index < source.length; index += 1) {
      const character = source[index];
      if (quote) {
        if (character === quote && source[index - 1] !== "\\") quote = undefined;
        continue;
      }
      if (character === '"' || character === "'" || character === "`") {
        quote = character;
      } else if (character === "(") {
        depth += 1;
      } else if (character === ")" && --depth === 0) {
        return index;
      }
    }
    return -1;
  }

  /** 在逗号仅属于参数顶层时进行切分，避免破坏数组、对象等默认值。 */
  private static splitTopLevel(source: string): string[] {
    if (!source.trim()) return [];
    const parameters: string[] = [];
    let start = 0;
    let depth = 0;
    let quote: string | undefined;

    for (let index = 0; index < source.length; index += 1) {
      const character = source[index];
      if (quote) {
        if (character === quote && source[index - 1] !== "\\") quote = undefined;
        continue;
      }
      if (character === '"' || character === "'" || character === "`") quote = character;
      else if ("([{ ".includes(character) && character !== " ") depth += 1;
      else if (")]}".includes(character)) depth -= 1;
      else if (character === "," && depth === 0) {
        parameters.push(source.slice(start, index).trim());
        start = index + 1;
      }
    }

    parameters.push(source.slice(start).trim());
    return parameters.filter(Boolean);
  }

  /** 找到参数顶层的默认值赋值号，箭头或嵌套对象中的等号不会被误识别。 */
  private static findTopLevelAssignment(source: string): number {
    let depth = 0;
    let quote: string | undefined;
    for (let index = 0; index < source.length; index += 1) {
      const character = source[index];
      if (quote) {
        if (character === quote && source[index - 1] !== "\\") quote = undefined;
      } else if (character === '"' || character === "'" || character === "`") {
        quote = character;
      } else if ("([{ ".includes(character) && character !== " ") {
        depth += 1;
      } else if (")]}".includes(character)) {
        depth -= 1;
      } else if (character === "=" && depth === 0 && source[index + 1] !== ">") {
        return index;
      }
    }
    return -1;
  }

  /** 只解析无副作用的常见字面量，绝不通过 eval 执行默认值源码。 */
  private static parseLiteral(source: string): unknown {
    if (source === "undefined" || source === "null") return null;
    if (source === "true") return true;
    if (source === "false") return false;
    if (/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(source)) return Number(source);

    if (
      (source.startsWith('"') && source.endsWith('"')) ||
      (source.startsWith("'") && source.endsWith("'"))
    ) {
      // JSON 能直接处理双引号；单引号字符串仅进行最小转义还原。
      if (source.startsWith('"')) {
        try {
          return JSON.parse(source) as unknown;
        } catch {
          return source.slice(1, -1);
        }
      }
      return source.slice(1, -1).replace(/\\'/g, "'").replace(/\\\\/g, "\\");
    }

    // 复杂表达式可能依赖运行环境，保留源码用于 schema 描述而不执行它。
    return source;
  }

  private static inferToolType(value: unknown): ToolParameterType {
    if (Array.isArray(value)) return "array";
    if (value !== null && typeof value === "object") return "object";
    if (typeof value === "boolean") return "boolean";
    if (typeof value === "number") return Number.isInteger(value) ? "integer" : "number";
    return "string";
  }

  getParameters(): ToolParameter[] {
    return [...this.parameters];
  }

  /** 按声明顺序把参数对象还原成位置参数，并将父工具作为方法的 this。 */
  run(parameters: Record<string, unknown>): string {
    const args = this.parameters.map((parameter) =>
      Object.prototype.hasOwnProperty.call(parameters, parameter.name)
        ? parameters[parameter.name]
        : parameter.default,
    );
    const result = this.method.apply(this.parent, args);
    if (result instanceof Promise) {
      throw new TypeError(
        `自动生成工具 '${this.name}' 不支持异步 action，请改为手动实现异步调用适配`,
      );
    }
    return String(result);
  }
}
