/**
 * `@toolAction` 装饰器及其配套元数据契约。
 *
 * 装饰器负责给方法打标记，`base.ts` 中的 Tool.getExpandedTools 与
 * AutoGeneratedTool 负责读取标记并展开子工具。两侧通过本文件导出的
 * Symbol 和类型共享同一份约定，因此这里是这套机制的唯一事实来源。
 */

/** 由 `@toolAction` 写入的元数据。 */
export interface ToolActionMetadata {
  name?: string;
  description?: string;
  methodName: string;
}

/** 被 `@toolAction` 标记的方法签名；参数与返回值一律按未知处理。 */
export type ToolActionMethod = (...args: unknown[]) => unknown;

/** 使用 Symbol 存储元数据，避免与业务方法上已有的字段发生命名冲突。 */
export const TOOL_ACTION_METADATA = Symbol("helloAgents.toolAction");

/** 挂上元数据后的方法类型，读取方据此安全访问标记。 */
export type DecoratedToolAction = ToolActionMethod & {
  [TOOL_ACTION_METADATA]?: ToolActionMetadata;
};

/** TS 5 标准方法装饰器所需的最小上下文，刻意不依赖特定 lib 版本。 */
interface StandardMethodDecoratorContext {
  kind: "method";
  name: string | symbol;
}

/**
 * 同时声明标准装饰器与旧式装饰器调用签名。
 * 泛型参数会原样保留被装饰方法的 this、参数元组和返回值类型。
 */
interface ToolActionDecorator {
  <This, Args extends unknown[], Return>(
    value: (this: This, ...args: Args) => Return,
    context: StandardMethodDecoratorContext,
  ): (this: This, ...args: Args) => Return;
  (target: object, propertyKey: string | symbol, descriptor: PropertyDescriptor): void;
}

/**
 * 标记一个方法，使可展开工具能把它自动暴露为独立子工具。
 *
 * 默认使用 TS 5 标准的 `(value, context)` 协议，同时兼容启用了
 * `experimentalDecorators` 的 legacy 三参数协议。名称或描述留空时会自动生成。
 */
export function toolAction(
  name?: string,
  description?: string,
): ToolActionDecorator {
  const markMethod = (method: ToolActionMethod, methodName: string): void => {
    const decoratedMethod = method as DecoratedToolAction;
    decoratedMethod[TOOL_ACTION_METADATA] = {
      name,
      description,
      methodName,
    };
  };

  const decorator = (
    valueOrTarget: object | ToolActionMethod,
    contextOrKey: StandardMethodDecoratorContext | string | symbol,
    descriptor?: PropertyDescriptor,
  ): ToolActionMethod | void => {
    // legacy 协议由第三个 descriptor 参数提供实际方法。
    if (descriptor) {
      if (typeof descriptor.value !== "function") {
        throw new TypeError("@toolAction 只能用于类方法");
      }
      markMethod(descriptor.value as ToolActionMethod, String(contextOrKey));
      return;
    }

    // TS 5 标准协议直接把方法值作为第一个参数传入。
    // typeof 检查只能收窄到内置 Function，需显式断言回工具方法签名。
    if (
      typeof valueOrTarget === "function" &&
      typeof contextOrKey === "object" &&
      contextOrKey.kind === "method"
    ) {
      const method = valueOrTarget as ToolActionMethod;
      markMethod(method, String(contextOrKey.name));
      return method;
    }

    throw new TypeError("@toolAction 只能用于类方法");
  };

  return decorator as ToolActionDecorator;
}
